version: "3.4"

services:
  belaz-database:
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    container_name: ${DATABASE_CONTAINER_NAME}
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DATABASE_EXTERNAL_PORT}:5432"
    volumes:
      - weldingdatabase:/var/lib/postgresql/data/
      - ${DATABASE_INIT_SCRIPT_PATH}:/docker-entrypoint-initdb.d/init.sql
    networks:
      - belaz

  welding-api:
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    image: vladsokol/belaz-welding-api
    build:
      context: ..
      dockerfile: ./Belaz.WeldingApp.WeldingApi/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      Auth__Secret: ${AUTH_SECRET}
      Auth__TokenLifetime: ${AUTH_TOKEN_LIFETIME}
      ConnectionStrings__WeldingDatabase: "Host=${DATABASE_CONTAINER_NAME};Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
    ports:
      - "${WELDING_API_EXTERNAL_PORT}:80"
    volumes:
      - welding-api-logs:/app/logs
    depends_on:
      - belaz-database
    networks:
      - belaz

  identity-api:
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    image: vladsokol/belaz-identity-api
    build:
      context: ..
      dockerfile: ./Belaz.WeldingApp.IdentityApi/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      Auth__Secret: ${AUTH_SECRET}
      Auth__TokenLifetime: ${AUTH_TOKEN_LIFETIME}
      REAL_API: ${REAL_APP_API_URL}
      ConnectionStrings__IdentityDb: "Host=${DATABASE_CONTAINER_NAME};Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
      EmailConfiguration__From: ${EMAIL_CONFIGURATION_FROM}
      EmailConfiguration__SmtpServer: ${EMAIL_CONFIGURATION_SMTP_SERVER}
      EmailConfiguration__Port: ${EMAIL_CONFIGURATION_PORT}
      EmailConfiguration__Username: ${EMAIL_CONFIGURATION_USERNAME}
      EmailConfiguration__Password: ${EMAIL_CONFIGURATION_PASSWORD}
    ports:
      - "${IDENTITY_API_EXTERNAL_PORT}:80"
    volumes:
      - identity-api-logs:/app/logs
    depends_on:
      - belaz-database
    networks:
      - belaz

  file-api:
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    image: vladsokol/belaz-file-api
    build:
      context: ..
      dockerfile: ./Belaz.WeldingApp.FileApi/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      Auth__Secret: ${AUTH_SECRET}
      Auth__TokenLifetime: ${AUTH_TOKEN_LIFETIME}
      ConnectionStrings__WeldingDatabase: "Host=${DATABASE_CONTAINER_NAME};Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
    ports:
      - "${FILE_API_EXTERNAL_PORT}:80"
    volumes:
      - file-api-logs:/app/logs
    depends_on:
      - belaz-database
    networks:
      - belaz

  registar-api:
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    image: vladsokol/belaz-registar-api
    build:
      context: ..
      dockerfile: ./Belaz.WeldingApp.RegistarApi/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      Auth__Secret: ${AUTH_SECRET}
      Auth__TokenLifetime: ${AUTH_TOKEN_LIFETIME}
      REAL_API: ${REAL_APP_API_URL}
      ConnectionStrings__WeldingDatabase: "Host=${DATABASE_CONTAINER_NAME};Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
      EmailConfiguration__From: ${EMAIL_CONFIGURATION_FROM}
      EmailConfiguration__SmtpServer: ${EMAIL_CONFIGURATION_SMTP_SERVER}
      EmailConfiguration__Port: ${EMAIL_CONFIGURATION_PORT}
      EmailConfiguration__Username: ${EMAIL_CONFIGURATION_USERNAME}
      EmailConfiguration__Password: ${EMAIL_CONFIGURATION_PASSWORD}
    ports:
      - "${REGISTAR_API_EXTERNAL_PORT}:80"
    volumes:
      - registar-api-logs:/app/logs
    depends_on:
      - belaz-database
    networks:
      - belaz

  gateway-api:
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    image: vladsokol/belaz-gateway-api
    build:
      context: ..
      dockerfile: ./Belaz.WeldingApp.ApiGateway/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      Auth__Secret: ${AUTH_SECRET}
      Auth__TokenLifetime: ${AUTH_TOKEN_LIFETIME}
      Services__identity__DownstreamPath: "http://identity-api:80"
      Services__welding__DownstreamPath: "http://welding-api:80"
      Services__file__DownstreamPath: "http://file-api:80"
      Services__registar__DownstreamPath: "http://registar-api:80"
    ports:
      - "${GATEWAY_API_EXTERNAL_PORT}:80"
    volumes:
      - gateway-api-logs:/app/logs
    depends_on:
      - belaz-database
    networks:
      - belaz

  proxy:
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    image: nginx:mainline
    volumes:
      - ${NGINX_CONFIG_PATH}:/etc/nginx/nginx.conf
    ports:
      - "${PROXY_EXTERNAL_PORT}:80"
    networks:
      - belaz

  belaz-client:
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    image: vladsokol/belaz-client
    build:
      context: ../client
      dockerfile: Dockerfile
    ports:
      - "${CLIENT_EXTERNAL_PORT}:3000"
    environment:
      REACT_APP_API_URI: ${REACT_APP_API_URI}
      REACT_APP_ENVIRONMENT: ${REACT_APP_ENVIRONMENT}
    networks:
      - belaz

  belaz-migrator:
    image: vladsokol/belaz-migrator
    build:
      context: ..
      dockerfile: ./Belaz.WeldingApp.MigrationUtil/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: "Host=${DATABASE_CONTAINER_NAME};Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
    command:
      - "--isDowngrade=false"
      - "--version=-1"
    depends_on:
      - belaz-database
    networks:
      - belaz

volumes:
  weldingdatabase:
  gateway-api-logs:
  file-api-logs:
  welding-api-logs:
  identity-api-logs:
  registar-api-logs:

networks:
  belaz:
    name: belaz_network
