version: '3.4'

services:
  belaz-postgres:
    image: postgres:15
    container_name: belaz-postgres
    restart: always
    volumes:
      - /home/bru/data/postgresql-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: Hynatg32_R
      POSTGRES_USER: bru
      POSTGRES_DB: bru
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "54321:5432"
  
  welding-api:
    image: welding-app/welding-api
    restart: always
    build:
      context: ..
      dockerfile: ./Belaz.WeldingApp.WeldingApi/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker.Production"
    ports:
      - "5010:80"
    volumes:
      - ../sharedsettings.json:/app/sharedsettings.json
    depends_on:
      - belaz-postgres

  identity-api:
    image: welding-app/identity-api
    restart: always
    build:
      context: ..
      dockerfile: ./Belaz.WeldingApp.IdentityApi/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker.Production"
    ports:
      - "5011:80"
    volumes:
      - ../sharedsettings.json:/app/sharedsettings.json
    depends_on:
      - belaz-postgres

  file-api:
    image: welding-app/file-api
    restart: always
    build:
      context: ..
      dockerfile: ./Belaz.WeldingApp.FileApi/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker.Production"
    volumes:
      - ../sharedsettings.json:/app/sharedsettings.json
    ports:
      - "5012:80"
    depends_on:
      - belaz-postgres
        
  gateway-api:
    image: welding-app/gateway-api
    restart: always
    build:
      context: ..
      dockerfile: ./Belaz.WeldingApp.ApiGateway/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
    ports:
      - "5100:80"
    volumes:
      - ./docker-storage/logs:/app/logs
      - ../sharedsettings.json:/app/sharedsettings.json
    depends_on:
      - postgresql_database

  proxy:
    image: nginx:mainline
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "4001:80"
    depends_on:
      - belaz-postgres