version: "3.4"

services:
  belaz-database:
    container_name: ${DATABASE_CONTAINER_NAME}
    image: postgres:15
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DATABASE_EXTERNAL_PORT}:5432"
    volumes:
      - weldingdatabase:/var/lib/postgresql/data/
      - ${DATABASE_INIT_SCRIPT_PATH}:/docker-entrypoint-initdb.d/init.sql

  welding-api:
    image: welding-app/welding-api
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    build:
      context: ..
      dockerfile: ./Belaz.WeldingApp.WeldingApi/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      Auth__Secret: ${AUTH_SECRET}
      Auth__TokenLifetime: ${AUTH_TOKEN_LIFETIME}
      ConnectionStrings__WeldingDatabase: "Host=${DATABASE_CONTAINER_NAME};Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
    ports:
      - "${WELDING_API_EXTERNAL_PORT}:80"
    volumes:
      - welding-api-logs:/app/logs
    depends_on:
      - belaz-database

  identity-api:
    image: welding-app/identity-api
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    build:
      context: ..
      dockerfile: ./Belaz.WeldingApp.IdentityApi/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      Auth__Secret: ${AUTH_SECRET}
      Auth__TokenLifetime: ${AUTH_TOKEN_LIFETIME}
      REAL_API: ${REAL_APP_API_URL}
      ConnectionStrings__IdentityDb: "Host=${DATABASE_CONTAINER_NAME};Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
      EmailConfiguration__From: ${EMAIL_CONFIGURATION_FROM}
      EmailConfiguration__SmtpServer: ${EMAIL_CONFIGURATION_SMTP_SERVER}
      EmailConfiguration__Port: ${EMAIL_CONFIGURATION_PORT}
      EmailConfiguration__Username: ${EMAIL_CONFIGURATION_USERNAME}
      EmailConfiguration__Password: ${EMAIL_CONFIGURATION_PASSWORD}
    ports:
      - "${IDENTITY_API_EXTERNAL_PORT}:80"
    volumes:
      - identity-api-logs:/app/logs
    depends_on:
      - belaz-database

  file-api:
    image: welding-app/file-api
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    build:
      context: ..
      dockerfile: ./Belaz.WeldingApp.FileApi/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      Auth__Secret: ${AUTH_SECRET}
      Auth__TokenLifetime: ${AUTH_TOKEN_LIFETIME}
      ConnectionStrings__WeldingDatabase: "Host=${DATABASE_CONTAINER_NAME};Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
    ports:
      - "${FILE_API_EXTERNAL_PORT}:80"
    volumes:
      - file-api-logs:/app/logs
    depends_on:
      - belaz-database

  registar-api:
    image: welding-app/registar-api
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    build:
      context: ..
      dockerfile: ./Belaz.WeldingApp.RegistarApi/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      Auth__Secret: ${AUTH_SECRET}
      Auth__TokenLifetime: ${AUTH_TOKEN_LIFETIME}
      REAL_API: ${REAL_APP_API_URL}
      ConnectionStrings__WeldingDatabase: "Host=${DATABASE_CONTAINER_NAME};Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
      EmailConfiguration__From: ${EMAIL_CONFIGURATION_FROM}
      EmailConfiguration__SmtpServer: ${EMAIL_CONFIGURATION_SMTP_SERVER}
      EmailConfiguration__Port: ${EMAIL_CONFIGURATION_PORT}
      EmailConfiguration__Username: ${EMAIL_CONFIGURATION_USERNAME}
      EmailConfiguration__Password: ${EMAIL_CONFIGURATION_PASSWORD}
    ports:
      - "${REGISTAR_API_EXTERNAL_PORT}:80"
    volumes:
      - registar-api-logs:/app/logs
    depends_on:
      - belaz-database

  gateway-api:
    image: welding-app/gateway-api
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    build:
      context: ..
      dockerfile: ./Belaz.WeldingApp.ApiGateway/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      Auth__Secret: ${AUTH_SECRET}
      Auth__TokenLifetime: ${AUTH_TOKEN_LIFETIME}
    ports:
      - "${GATEWAY_API_EXTERNAL_PORT}:80"
    volumes:
      - gateway-api-logs:/app/logs
    depends_on:
      - belaz-database

  proxy:
    image: nginx:mainline
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    volumes:
      - ${NGINX_CONFIG_PATH}:/etc/nginx/nginx.conf
    ports:
      - "${PROXY_EXTERNAL_PORT}:80"

  belaz-client:
    image: belaz-client
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    build:
      context: ../client
      dockerfile: Dockerfile
    ports:
      - "${CLIENT_EXTERNAL_PORT}:3000"
    environment:
      REACT_APP_API_URI: ${REACT_APP_API_URI}

volumes:
  weldingdatabase:
  gateway-api-logs:
  file-api-logs:
  welding-api-logs:
  identity-api-logs:
  registar-api-logs:
