version: '3.4'

services:
  postgresql_database:
    container_name: postgresql_database
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminadmin
      POSTGRES_DB: welding-belaz
    ports:
      - "5432:5432"
    volumes:
      - ./docker-storage/databasedata:/var/lib/postgresql/data/
      - ../../database/init-script.sql:/docker-entrypoint-initdb.d/init.sql

  welding-api:
    image: welding-app/welding-api
    restart: on-failure
    build:
      context: ..
      dockerfile: ./Belaz.WeldingApp.WeldingApi/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
    ports:
      - "5010:80"
    volumes:
      - ./docker-storage/welding-api-logs:/app/logs
      - ../sharedsettings.json:/app/sharedsettings.json
    depends_on:
      - postgresql_database
        
  identity-api:
    image: welding-app/identity-api
    restart: on-failure
    build:
      context: ..
      dockerfile: ./Belaz.WeldingApp.IdentityApi/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
    ports:
      - "5011:80"
    volumes:
      - ./docker-storage/identity-api-logs:/app/logs
      - ../sharedsettings.json:/app/sharedsettings.json
    depends_on:
      - postgresql_database
      - welding-api
    
  file-api:
    image: welding-app/file-api
    restart: on-failure
    build:
      context: ..
      dockerfile: ./Belaz.WeldingApp.FileApi/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
    ports:
      - "5012:80"
    volumes:
      - ./docker-storage/file-api-logs:/app/logs
      - ../sharedsettings.json:/app/sharedsettings.json
    depends_on:
      - postgresql_database
      - welding-api
      
  gateway-api:
    image: welding-app/gateway-api
    build:
      context: ..
      dockerfile: ./Belaz.WeldingApp.ApiGateway/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
    ports:
      - "5100:80"
    volumes:
      - ./docker-storage/gateway-api-logs:/app/logs
      - ../sharedsettings.json:/app/sharedsettings.json
    depends_on:
      - postgresql_database
        
  proxy:
    image: nginx:mainline
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "4001:80"
        
  belaz-client:
    image: belaz-client
    build:
      context: ../client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - "REACT_APP_API_URI=api"