ALTER TABLE ONLY public."Workplaces" DROP CONSTRAINT "FK_Workplaces_ProductionAreas_ProductionAreaId";
ALTER TABLE ONLY public."Workplaces" DROP CONSTRAINT "FK_Workplaces_Posts_PostId";
ALTER TABLE ONLY public."WorkingShifts" DROP CONSTRAINT "FK_WorkingShifts_Days_DayId";
ALTER TABLE ONLY public."WorkingShifts" DROP CONSTRAINT "FK_WorkingShifts_Calendars_CalendarId";
ALTER TABLE ONLY public."WeldingTasks" DROP CONSTRAINT "FK_WeldingTasks_Welders_WelderId";
ALTER TABLE ONLY public."WeldingTasks" DROP CONSTRAINT "FK_WeldingTasks_SeamAccounts_SeamAccountId";
ALTER TABLE ONLY public."WeldingTasks" DROP CONSTRAINT "FK_WeldingTasks_Masters_MasterId";
ALTER TABLE ONLY public."WeldingTasks" DROP CONSTRAINT "FK_WeldingTasks_Inspectors_InspectorId";
ALTER TABLE ONLY public."WeldingRecords" DROP CONSTRAINT "FK_WeldingRecords_WeldingRecordLimits_WeldingRecordLimitId";
ALTER TABLE ONLY public."WeldingRecords" DROP CONSTRAINT "FK_WeldingRecords_WeldingEquipments_WeldingEquipmentId";
ALTER TABLE ONLY public."WeldingRecords" DROP CONSTRAINT "FK_WeldingRecords_Welders_WelderId";
ALTER TABLE ONLY public."WeldingRecords" DROP CONSTRAINT "FK_WeldingRecords_Masters_MasterId";
ALTER TABLE ONLY public."WeldingEquipments" DROP CONSTRAINT "FK_WeldingEquipments_Posts_PostId";
ALTER TABLE ONLY public."WeldingEquipments" DROP CONSTRAINT "FK_WeldingEquipments_Masters_MasterId";
ALTER TABLE ONLY public."WeldingEquipmentWorkplace" DROP CONSTRAINT "FK_WeldingEquipmentWorkplace_Workplaces_WorkplacesId";
ALTER TABLE ONLY public."WeldingEquipmentWorkplace" DROP CONSTRAINT "FK_WeldingEquipmentWorkplace_WeldingEquipments_WeldingEquipmen~";
ALTER TABLE ONLY public."WeldingEquipmentConditionTimes" DROP CONSTRAINT "FK_WeldingEquipmentConditionTimes_WeldingEquipments_WeldingEqu~";
ALTER TABLE ONLY public."WeldingEquipmentConditionTimes" DROP CONSTRAINT "FK_WeldingEquipmentConditionTimes_Welders_WelderId";
ALTER TABLE ONLY public."WeldingEquipmentConditionTimes" DROP CONSTRAINT "FK_WeldingEquipmentConditionTimes_DowntimeReasons_DowntimeReas~";
ALTER TABLE ONLY public."Welders" DROP CONSTRAINT "FK_Welders_Workplaces_WorkplaceId";
ALTER TABLE ONLY public."Welders" DROP CONSTRAINT "FK_Welders_Users_UserId";
ALTER TABLE ONLY public."WelderWeldingEquipment" DROP CONSTRAINT "FK_WelderWeldingEquipment_WeldingEquipments_WeldingEquipmentsId";
ALTER TABLE ONLY public."WelderWeldingEquipment" DROP CONSTRAINT "FK_WelderWeldingEquipment_Welders_WeldersId";
ALTER TABLE ONLY public."WeldPassages" DROP CONSTRAINT "FK_WeldPassages_WeldingTasks_WeldingTaskId";
ALTER TABLE ONLY public."WeldPassages" DROP CONSTRAINT "FK_WeldPassages_WeldingRecords_WeldingRecordId";
ALTER TABLE ONLY public."WeldPassageInstructions" DROP CONSTRAINT "FK_WeldPassageInstructions_TechnologicalInstructions_Technolog~";
ALTER TABLE ONLY public."Users" DROP CONSTRAINT "FK_Users_ProductionAreas_ProductionAreaId";
ALTER TABLE ONLY public."Seams" DROP CONSTRAINT "FK_Seams_Workplaces_WorkplaceId";
ALTER TABLE ONLY public."Seams" DROP CONSTRAINT "FK_Seams_TechnologicalInstructions_TechnologicalInstructionId";
ALTER TABLE ONLY public."Seams" DROP CONSTRAINT "FK_Seams_Products_ProductId";
ALTER TABLE ONLY public."Seams" DROP CONSTRAINT "FK_Seams_ProductionAreas_ProductionAreaId";
ALTER TABLE ONLY public."Seams" DROP CONSTRAINT "FK_Seams_Inspectors_InspectorId";
ALTER TABLE ONLY public."SeamResults" DROP CONSTRAINT "FK_SeamResults_SeamAccounts_SeamAccountId";
ALTER TABLE ONLY public."SeamAccounts" DROP CONSTRAINT "FK_SeamAccounts_Seams_SeamId";
ALTER TABLE ONLY public."SeamAccounts" DROP CONSTRAINT "FK_SeamAccounts_ProductAccounts_ProductAccountId";
ALTER TABLE ONLY public."Products" DROP CONSTRAINT "FK_Products_Workplaces_WorkplaceId";
ALTER TABLE ONLY public."Products" DROP CONSTRAINT "FK_Products_TechnologicalProcesses_TechnologicalProcessId";
ALTER TABLE ONLY public."Products" DROP CONSTRAINT "FK_Products_ProductionAreas_ProductionAreaId";
ALTER TABLE ONLY public."Products" DROP CONSTRAINT "FK_Products_Masters_MasterId";
ALTER TABLE ONLY public."Products" DROP CONSTRAINT "FK_Products_Inspectors_InspectorId";
ALTER TABLE ONLY public."ProductionAreas" DROP CONSTRAINT "FK_ProductionAreas_Workshops_WorkshopId";
ALTER TABLE ONLY public."ProductResults" DROP CONSTRAINT "FK_ProductResults_ProductAccounts_ProductAccountId";
ALTER TABLE ONLY public."ProductInsides" DROP CONSTRAINT "FK_ProductInsides_Products_MainProductId";
ALTER TABLE ONLY public."ProductInsides" DROP CONSTRAINT "FK_ProductInsides_Products_InsideProductId";
ALTER TABLE ONLY public."ProductAccounts" DROP CONSTRAINT "FK_ProductAccounts_Products_ProductId";
ALTER TABLE ONLY public."ProductAccountWeldingEquipment" DROP CONSTRAINT "FK_ProductAccountWeldingEquipment_WeldingEquipments_WeldingEqu~";
ALTER TABLE ONLY public."ProductAccountWeldingEquipment" DROP CONSTRAINT "FK_ProductAccountWeldingEquipment_ProductAccounts_ProductAccou~";
ALTER TABLE ONLY public."Posts" DROP CONSTRAINT "FK_Posts_ProductionAreas_ProductionAreaId";
ALTER TABLE ONLY public."Masters" DROP CONSTRAINT "FK_Masters_Users_UserId";
ALTER TABLE ONLY public."Inspectors" DROP CONSTRAINT "FK_Inspectors_Users_UserId";
ALTER TABLE ONLY public."EventLogs" DROP CONSTRAINT "FK_EventLogs_Users_UserId";
ALTER TABLE ONLY public."DefectiveReasons" DROP CONSTRAINT "FK_DefectiveReasons_WeldingTasks_WeldingTaskId";
ALTER TABLE ONLY public."Days" DROP CONSTRAINT "FK_Days_Calendars_CalendarId";
ALTER TABLE ONLY public."Chiefs" DROP CONSTRAINT "FK_Chiefs_Workshops_WorkshopId";
ALTER TABLE ONLY public."Chiefs" DROP CONSTRAINT "FK_Chiefs_WeldingEquipments_WeldingEquipmentId";
ALTER TABLE ONLY public."Chiefs" DROP CONSTRAINT "FK_Chiefs_Users_UserId";
ALTER TABLE ONLY public."Calendars" DROP CONSTRAINT "FK_Calendars_WeldingEquipments_WeldingEquipmentId";
ALTER TABLE ONLY public."Calendars" DROP CONSTRAINT "FK_Calendars_Welders_WelderId";
DROP TRIGGER set_welding_record_limit_trigger ON public."WeldingRecords";
DROP TRIGGER check_welding_task_number_trigger ON public."WeldingTasks";
DROP TRIGGER add_unique_number_trigger ON public."WeldingTasks";
DROP INDEX public."IX_Workshops_IdFromSystem";
DROP INDEX public."IX_Workplaces_ProductionAreaId";
DROP INDEX public."IX_Workplaces_PostId";
DROP INDEX public."IX_Workplaces_IdFromSystem";
DROP INDEX public."IX_WorkingShifts_IdFromSystem";
DROP INDEX public."IX_WorkingShifts_DayId";
DROP INDEX public."IX_WorkingShifts_CalendarId";
DROP INDEX public."IX_WeldingTasks_WelderId";
DROP INDEX public."IX_WeldingTasks_SeamAccountId";
DROP INDEX public."IX_WeldingTasks_MasterId";
DROP INDEX public."IX_WeldingTasks_InspectorId";
DROP INDEX public."IX_WeldingTasks_IdFromSystem";
DROP INDEX public."IX_WeldingRecords_WeldingRecordLimitId";
DROP INDEX public."IX_WeldingRecords_WeldingEquipmentId";
DROP INDEX public."IX_WeldingRecords_WelderId";
DROP INDEX public."IX_WeldingRecords_MasterId";
DROP INDEX public."IX_WeldingRecords_IdFromSystem";
DROP INDEX public."IX_WeldingRecordLimits_IdFromSystem";
DROP INDEX public."IX_WeldingEquipments_RfidTag";
DROP INDEX public."IX_WeldingEquipments_PostId";
DROP INDEX public."IX_WeldingEquipments_MasterId";
DROP INDEX public."IX_WeldingEquipments_IdFromSystem";
DROP INDEX public."IX_WeldingEquipmentWorkplace_WorkplacesId";
DROP INDEX public."IX_WeldingEquipmentConditionTimes_WeldingEquipmentId";
DROP INDEX public."IX_WeldingEquipmentConditionTimes_WelderId";
DROP INDEX public."IX_WeldingEquipmentConditionTimes_IdFromSystem";
DROP INDEX public."IX_WeldingEquipmentConditionTimes_DowntimeReasonId";
DROP INDEX public."IX_Welders_WorkplaceId";
DROP INDEX public."IX_Welders_UserId";
DROP INDEX public."IX_Welders_IdFromSystem";
DROP INDEX public."IX_WelderWeldingEquipment_WeldingEquipmentsId";
DROP INDEX public."IX_WeldPassages_WeldingTaskId";
DROP INDEX public."IX_WeldPassages_WeldingRecordId";
DROP INDEX public."IX_WeldPassages_IdFromSystem";
DROP INDEX public."IX_WeldPassageInstructions_TechnologicalInstructionId";
DROP INDEX public."IX_WeldPassageInstructions_IdFromSystem";
DROP INDEX public."IX_Users_RfidTag";
DROP INDEX public."IX_Users_ProductionAreaId";
DROP INDEX public."IX_Users_IdFromSystem";
DROP INDEX public."IX_TechnologicalProcesses_IdFromSystem";
DROP INDEX public."IX_TechnologicalInstructions_IdFromSystem";
DROP INDEX public."IX_Seams_WorkplaceId";
DROP INDEX public."IX_Seams_TechnologicalInstructionId";
DROP INDEX public."IX_Seams_ProductionAreaId";
DROP INDEX public."IX_Seams_ProductId";
DROP INDEX public."IX_Seams_InspectorId";
DROP INDEX public."IX_Seams_IdFromSystem";
DROP INDEX public."IX_SeamResults_SeamAccountId";
DROP INDEX public."IX_SeamResults_IdFromSystem";
DROP INDEX public."IX_SeamAccounts_SeamId";
DROP INDEX public."IX_SeamAccounts_ProductAccountId";
DROP INDEX public."IX_SeamAccounts_IdFromSystem";
DROP INDEX public."IX_Products_WorkplaceId";
DROP INDEX public."IX_Products_TechnologicalProcessId";
DROP INDEX public."IX_Products_ProductionAreaId";
DROP INDEX public."IX_Products_MasterId";
DROP INDEX public."IX_Products_InspectorId";
DROP INDEX public."IX_Products_IdFromSystem";
DROP INDEX public."IX_ProductionAreas_WorkshopId";
DROP INDEX public."IX_ProductionAreas_IdFromSystem";
DROP INDEX public."IX_ProductResults_ProductAccountId";
DROP INDEX public."IX_ProductResults_IdFromSystem";
DROP INDEX public."IX_ProductInsides_MainProductId";
DROP INDEX public."IX_ProductInsides_InsideProductId";
DROP INDEX public."IX_ProductAccounts_ProductId";
DROP INDEX public."IX_ProductAccounts_IdFromSystem";
DROP INDEX public."IX_ProductAccountWeldingEquipment_WeldingEquipmentsId";
DROP INDEX public."IX_Posts_ProductionAreaId";
DROP INDEX public."IX_Posts_IdFromSystem";
DROP INDEX public."IX_Masters_UserId";
DROP INDEX public."IX_Masters_IdFromSystem";
DROP INDEX public."IX_Inspectors_UserId";
DROP INDEX public."IX_Inspectors_IdFromSystem";
DROP INDEX public."IX_EventLogs_UserId";
DROP INDEX public."IX_EventLogs_IdFromSystem";
DROP INDEX public."IX_DowntimeReasons_IdFromSystem";
DROP INDEX public."IX_DefectiveReasons_WeldingTaskId";
DROP INDEX public."IX_DefectiveReasons_IdFromSystem";
DROP INDEX public."IX_Days_IdFromSystem";
DROP INDEX public."IX_Days_CalendarId";
DROP INDEX public."IX_Chiefs_WorkshopId";
DROP INDEX public."IX_Chiefs_WeldingEquipmentId";
DROP INDEX public."IX_Chiefs_UserId";
DROP INDEX public."IX_Chiefs_IdFromSystem";
DROP INDEX public."IX_Calendars_WeldingEquipmentId";
DROP INDEX public."IX_Calendars_WelderId";
DROP INDEX public."IX_Calendars_IdFromSystem";
ALTER TABLE ONLY public."Workshops" DROP CONSTRAINT "PK_Workshops";
ALTER TABLE ONLY public."Workplaces" DROP CONSTRAINT "PK_Workplaces";
ALTER TABLE ONLY public."WorkingShifts" DROP CONSTRAINT "PK_WorkingShifts";
ALTER TABLE ONLY public."WeldingTasks" DROP CONSTRAINT "PK_WeldingTasks";
ALTER TABLE ONLY public."WeldingRecords" DROP CONSTRAINT "PK_WeldingRecords";
ALTER TABLE ONLY public."WeldingRecordLimits" DROP CONSTRAINT "PK_WeldingRecordLimits";
ALTER TABLE ONLY public."WeldingEquipments" DROP CONSTRAINT "PK_WeldingEquipments";
ALTER TABLE ONLY public."WeldingEquipmentWorkplace" DROP CONSTRAINT "PK_WeldingEquipmentWorkplace";
ALTER TABLE ONLY public."WeldingEquipmentConditionTimes" DROP CONSTRAINT "PK_WeldingEquipmentConditionTimes";
ALTER TABLE ONLY public."Welders" DROP CONSTRAINT "PK_Welders";
ALTER TABLE ONLY public."WelderWeldingEquipment" DROP CONSTRAINT "PK_WelderWeldingEquipment";
ALTER TABLE ONLY public."WeldPassages" DROP CONSTRAINT "PK_WeldPassages";
ALTER TABLE ONLY public."WeldPassageInstructions" DROP CONSTRAINT "PK_WeldPassageInstructions";
ALTER TABLE ONLY public."Users" DROP CONSTRAINT "PK_Users";
ALTER TABLE ONLY public."TechnologicalProcesses" DROP CONSTRAINT "PK_TechnologicalProcesses";
ALTER TABLE ONLY public."TechnologicalInstructions" DROP CONSTRAINT "PK_TechnologicalInstructions";
ALTER TABLE ONLY public."Seams" DROP CONSTRAINT "PK_Seams";
ALTER TABLE ONLY public."SeamResults" DROP CONSTRAINT "PK_SeamResults";
ALTER TABLE ONLY public."SeamAccounts" DROP CONSTRAINT "PK_SeamAccounts";
ALTER TABLE ONLY public."Products" DROP CONSTRAINT "PK_Products";
ALTER TABLE ONLY public."ProductionAreas" DROP CONSTRAINT "PK_ProductionAreas";
ALTER TABLE ONLY public."ProductResults" DROP CONSTRAINT "PK_ProductResults";
ALTER TABLE ONLY public."ProductInsides" DROP CONSTRAINT "PK_ProductInsides";
ALTER TABLE ONLY public."ProductAccounts" DROP CONSTRAINT "PK_ProductAccounts";
ALTER TABLE ONLY public."ProductAccountWeldingEquipment" DROP CONSTRAINT "PK_ProductAccountWeldingEquipment";
ALTER TABLE ONLY public."Posts" DROP CONSTRAINT "PK_Posts";
ALTER TABLE ONLY public."Masters" DROP CONSTRAINT "PK_Masters";
ALTER TABLE ONLY public."Inspectors" DROP CONSTRAINT "PK_Inspectors";
ALTER TABLE ONLY public."EventLogs" DROP CONSTRAINT "PK_EventLogs";
ALTER TABLE ONLY public."DowntimeReasons" DROP CONSTRAINT "PK_DowntimeReasons";
ALTER TABLE ONLY public."DefectiveReasons" DROP CONSTRAINT "PK_DefectiveReasons";
ALTER TABLE ONLY public."Days" DROP CONSTRAINT "PK_Days";
ALTER TABLE ONLY public."Chiefs" DROP CONSTRAINT "PK_Chiefs";
ALTER TABLE ONLY public."Calendars" DROP CONSTRAINT "PK_Calendars";
DROP TABLE public."Workshops";
DROP TABLE public."Workplaces";
DROP TABLE public."WorkingShifts";
DROP TABLE public."WeldingTasks";
DROP TABLE public."WeldingRecords";
DROP TABLE public."WeldingRecordLimits";
DROP TABLE public."WeldingEquipments";
DROP TABLE public."WeldingEquipmentWorkplace";
DROP TABLE public."WeldingEquipmentConditionTimes";
DROP TABLE public."Welders";
DROP TABLE public."WelderWeldingEquipment";
DROP TABLE public."WeldPassages";
DROP TABLE public."WeldPassageInstructions";
DROP TABLE public."Users";
DROP TABLE public."TechnologicalProcesses";
DROP TABLE public."TechnologicalInstructions";
DROP TABLE public."Seams";
DROP TABLE public."SeamResults";
DROP TABLE public."SeamAccounts";
DROP TABLE public."Products";
DROP TABLE public."ProductionAreas";
DROP TABLE public."ProductResults";
DROP TABLE public."ProductInsides";
DROP TABLE public."ProductAccounts";
DROP TABLE public."ProductAccountWeldingEquipment";
DROP TABLE public."Posts";
DROP TABLE public."Masters";
DROP TABLE public."Inspectors";
DROP TABLE public."EventLogs";
DROP TABLE public."DowntimeReasons";
DROP TABLE public."DefectiveReasons";
DROP TABLE public."Days";
DROP TABLE public."Chiefs";
DROP TABLE public."Calendars";
DROP FUNCTION public.set_welding_record_limit_function();
DROP FUNCTION public.check_welding_task_number_function();
DROP FUNCTION public.calculate_term_deviation(input_values double precision[], min double precision, max double precision);
DROP FUNCTION public.add_unique_number_function();